### PR TITLE
release: v1.2.1

### PR DESCRIPTION
**Pull request by AhyoungRyu**
#### Feat:
- Improved user experience based on customer feedback:
  - Excluded display of 👍👎 emojis during message streaming.
  - Modified URL text messages from bots to be parsed as links.
  - Fixed display of code snippets which had been broken since the self-service https://github.com/sendbird/chat-ai-widget/pull/87.
- Added `renderWidgetToggleButton` prop to support custom widget toggle button rendering.

#### Fix:
- Replaced Channel module with GroupChannel to address issues.
- Used `isLoading` and `isPending` along with `isFetching` in `useChannelStyle` query hook to get the loading status.

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
I'll rebase once #97 is merged.

**Comment by sendbird-sdk-deployment** [comment]
[Creating Ticket] 🔖 Done https://sendbird.atlassian.net/browse/SDKRLSD-1142

**Review by luke-cha — APPROVED** [review]
Approved!

**Pull request merged**
