### PR TITLE
feat: Add pending spinner icon for pending messages (draft)

### PR DESCRIPTION
**Pull request by chohongm**
### Ticket
https://sendbird.atlassian.net/browse/AC-2609

### CODE REVIEW

**Comment by bang9** [comment]
It seems that we frequently need to ask for confirmations. Please check the following list before requesting a review:

- Ensure that the ticket requirements have been clearly implemented.
- Verify that all CI checks have passed.
- Conduct a self-review and further check for any areas of improvement or discrepancies with the requirements.

**Comment by bang9** [comment]
@liamcho 이거는 계속 draft 로 남아있는데 티켓은 in review 상태인거같네요, 작업을 진행하던가 티켓 상태를 업뎃하면 좋을 것 같습니다.

**Comment by chohongm** [comment]
@bang9 폼 작업 -> 템플릿 작업 -> 이후 재개 할 예정이라 백로그로 변경했습니다

**Comment by chohongm** [comment]
duplicate of https://github.com/sendbird/chat-ai-widget/pull/363

**Pull request closed without merging**
