### PR TITLE
release: v1.7.4

### PR DESCRIPTION
**Pull request by bang9**
### Fix:
- Fixed a UX issue where the feedback modal was displaying unintended behavior
- Fixed a bug with URL handling in Markdown syntax
- Fixed a bug where the self-service widget was broken in Angular.js

### CODE REVIEW

**Comment by sendbird-sdk-deployment** [comment]
[Creating Ticket] 🔖 Done https://sendbird.atlassian.net/browse/SDKRLSD-1357

**Review by chohongm — APPROVED** [review]
LGTM

**Comment by sendbird-sdk-deployment** [comment]
[Creating Ticket] 🔖 Done https://sendbird.atlassian.net/browse/AUT-380

**Pull request merged**
