### PR TITLE
fix: Update render feedback rule based on myFeedbackStatus

### PR DESCRIPTION
**Pull request by chohongm**
### Changelog
- Message feedback buttons are displayed if and only if `message.myFeedbackStatus` is not 'NOT_APPLICABLE'

### Ticket
https://sendbird.atlassian.net/browse/AC-2290

discussion:
https://sendbird.slack.com/archives/C0585965FFA/p1717402133967919?thread_ts=1717121915.460269&cid=C0585965FFA

### CODE REVIEW

**Review by bang9 — COMMENTED** [review]
Did you check if it is working properly with the patched chat-sdk before requesting a review?

**Comment by chohongm** [comment]
let me test this tomorrow. I need to figure out how to enable/disable feedback in server. It should be done by request at init step.

**Comment by bang9** [comment]
> let me test this tomorrow. I need to figure out how to enable/disable feedback in server. It should be done by request at init step.

You can check the detailed policy for feedback here: https://docs.google.com/document/d/1M06574UQU3NV-fucbP6HCf1oCvxYyBWC_ETOISrvLQ4/edit (it's included in [thread](https://sendbird.slack.com/archives/C0585965FFA/p1717121915460269))

**Comment by chohongm** [comment]
@bang9 the fix has been confirmed through testing!
https://sendbird.slack.com/archives/C0585965FFA/p1717473239686719?thread_ts=1717121915.460269&cid=C0585965FFA

**Comment by bang9** [comment]
I have confirmed that it works well in self-service too.

**Comment by chohongm** [comment]
@bang9 thanks for testing self-servce. When you have time, can you please share how to test self-service?
I tried running locally by swapping to local project but failed to do it.
```
    "@sendbird/chat-ai-widget": "file:/Users/liamcho/GitHub/chat-ai-widget/dist",
    
 ➜  self-service git:(develop) ✗ yarn install
➤ YN0000: · Yarn 4.2.2
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @sendbird/chat-ai-widget@file:/Users/liamcho/GitHub/chat-ai-widget/dist#/Users/liamcho/GitHub/chat-ai-widget/dist::hash=c5affd&locator=self-service%40workspace%3Apackages%2Fself-service: Manifest not found
```
I will document the SOP for others too!

**Comment by bang9** [comment]
I'll approve it once the chat-sdk is updated.

**Comment by bang9** [comment]
> @bang9 thanks for testing self-servce. When you have time, can you please share how to test self-service? I tried running locally by swapping to local project but failed to do it.
> 
> ```
>     "@sendbird/chat-ai-widget": "file:/Users/liamcho/GitHub/chat-ai-widget/dist",
>     
>  ➜  self-service git:(develop) ✗ yarn install
> ➤ YN0000: · Yarn 4.2.2
> ➤ YN0000: ┌ Resolution step
> ➤ YN0001: │ Error: @sendbird/chat-ai-widget@file:/Users/liamcho/GitHub/chat-ai-widget/dist#/Users/liamcho/GitHub/chat-ai-widget/dist::hash=c5affd&locator=self-service%40workspace%3Apackages%2Fself-service: Manifest not found
> ```
> 
> I will document the SOP for others too!

I will inform you from a fundamental perspective tomorrow.

**Comment by bang9** [comment]
https://github.com/sendbird/sendbird-chat-sdk-javascript/releases/tag/v4.12.7

**Comment by chohongm** [comment]
@bang9 Please review https://github.com/sendbird/sendbird-uikit-react/pull/1125, thanks!

**Comment by chohongm** [comment]
@bang9 all good!
tested with     "@sendbird/chat": "^4.12.7",
in packages/uikit package.json

https://github.com/sendbird/chat-ai-widget/assets/16806397/5908adb8-e18e-4bf7-8dc0-ecc37820c4c9

**Comment by bang9** [comment]
great, could you update the head of submodule?

**Review by bang9 — APPROVED** [review]

**Pull request merged**
