### PR TITLE
[SBTW-1849] Addressing Feedback from Offline Review of the Healthcare Demo

### PR DESCRIPTION
**Pull request by hello-mansoo**
## Changes
- Update to automatically close the bottom modal when a message is sent
- Improve the layout inside the bottom modal
- In "Ask the Assistant," display a loading dot while waiting for the API response (considered using React Query, but added a state for sending status instead, as continuous server state tracking isn't needed)
- Make some variable names more intuitive

ticket: [https://sendbird.atlassian.net/browse/SBTW-1849]

## Additional Notes
- I'm sharing a demo video to assist with your review. : https://drive.google.com/file/d/1IHzPOLAvbcpFdsqk-yY98n0b6NUHAb1o/view?usp=drive_link

## Checklist
Before requesting a code review, please check the following:
- [ ] **[Required]** CI has passed all checks.
- [ ] **[Required]** A self-review has been conducted to ensure there are no minor mistakes.
- [ ] **[Required]** Unnecessary comments/debugging code have been removed.
- [ ] **[Required]** All requirements specified in the ticket have been accurately implemented.
- [ ] Ensure the ticket has been updated with the sprint, status, and story points.

### CODE REVIEW

**Comment by bang9** [comment]
Can't open recording~

**Comment by hello-mansoo** [comment]
> Can't open recording~

Oh, I'll share with google drive link within 5 min!!

**Comment by hello-mansoo** [comment]
@bang9 I updated the link in the description:) Thx a lot!

**Review by bang9 — APPROVED** [review]
lgtm!

**Comment by hello-mansoo** [comment]
@bang9 Super thanks for your quick review! My hero.. ✨

**Pull request merged**
