### PR TITLE
fix: Fix typing indicator bubble to depend on bot user typing status update

### PR DESCRIPTION
**Pull request by chohongm**
### Ticket
https://sendbird.atlassian.net/browse/AC-3394

### CODE REVIEW

**Comment by bang9** [comment]
Is it okay if I handle it in #312 ? There will be conflicts related to this, so I'll make the changes together

**Comment by bang9** [comment]
https://github.com/sendbird/chat-ai-widget/pull/312/commits/7a26bee4e0fdf0a464c4c1ee86220d47a5b6cf53

When the message status is pending, the typing bubble doesn't appear because the message hasn't reached the server yet, even if it's just for a brief moment.

Since there is a subtle difference, I won't apply it immediately. It would be better to test whether the user experience is natural after implementing the display of the pending status, and then apply it if it works well.

**Comment by chohongm** [comment]
> Is it okay if I handle it in #312 ? There will be conflicts related to this, so I'll make the changes together

yes!

**Comment by chohongm** [comment]
> [7a26bee](https://github.com/sendbird/chat-ai-widget/commit/7a26bee4e0fdf0a464c4c1ee86220d47a5b6cf53)
> 
> When the message status is pending, the typing bubble doesn't appear because the message hasn't reached the server yet, even if it's just for a brief moment.
> 
> Since there is a subtle difference, I won't apply it immediately. It would be better to test whether the user experience is natural after implementing the display of the pending status, and then apply it if it works well.

We still needs this for auto-resend.

**Comment by bang9** [comment]
> > [7a26bee](https://github.com/sendbird/chat-ai-widget/commit/7a26bee4e0fdf0a464c4c1ee86220d47a5b6cf53)
> > When the message status is pending, the typing bubble doesn't appear because the message hasn't reached the server yet, even if it's just for a brief moment.
> > Since there is a subtle difference, I won't apply it immediately. It would be better to test whether the user experience is natural after implementing the display of the pending status, and then apply it if it works well.
> 
> We still needs this for auto-resend.

That is block logic, not related to this(typing bubble).

**Pull request closed without merging**
